force-app/main/default/objects/CallableHandler__mdt/CallableHandler__mdt.object-meta.xml
<CustomObject>
    <label>CallableHandler</label>
    <pluralLabel>CallableHandlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CallableHandler__mdt/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CallableHandler__mdt/fields/classname__c.field-meta.xml
<CustomField>
    <fullName>classname__c</fullName>
    <label>classname</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallableHandler__mdt/fields/namespace__c.field-meta.xml
<CustomField>
    <fullName>namespace__c</fullName>
    <label>namespace</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallableQueue__e/CallableQueue__e.object-meta.xml
<CustomObject>
    <label>CallableQueue</label>
    <pluralLabel>CallableQueues</pluralLabel>
</CustomObject>

force-app/main/default/objects/CallableQueue__e/fields/action__c.field-meta.xml
<CustomField>
    <fullName>action__c</fullName>
    <label>action</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallableQueue__e/fields/args__c.field-meta.xml
<CustomField>
    <fullName>args__c</fullName>
    <label>args</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CallableQueueTriggerHandler.cls
/**
 * CallableQueueTriggerHandler
 */
public inherited sharing class CallableQueueTriggerHandler {

    public class TriggerHandlerException extends Exception {}

    public static void broker(List<CallableQueue__e> events) {
        try {
	        CallableHandler__mdt callHandler = [
		        SELECT classname__c,namespace__c
		        FROM CallableHandler__mdt 
		        WHERE active__c = true
		        LIMIT 1
	        ];
	
	        for (CallableQueue__e event : events) {

		        Map<String, Object> args = new Map<String, Object>();
		        if (String.isNotEmpty(event.args__c)) {
	   	            args = (Map<String, Object>)JSON.deserializeUntyped(event.args__c);
		        }
		
		        Callable extension = (Callable)Type.forName(callHandler.namespace__c, callHandler.classname__c).newInstance();
		        Object result = extension.call(event.action__c, args);

		        System.debug('\t*** result ***\n'+JSON.serializePretty(result));
	        }

        } catch(System.QueryException e) {
            //System.debug('\t*** CallableQueueTriggerHandler ***\nNo registered callable class');
            throw new TriggerHandlerException('No registered callable class');
        }
    }

}