force-app/main/default/objects/RunInSandbox__c/RunInSandbox__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>*** Warning *** It is dangerous to run integrations in sandbox Orgs without planning 1st. Check that all connections to external systems have been updated to point to reciprocal non-production environments before setting &quot;Allow&quot;.</description>
    <label>RunInSandbox</label>
</CustomObject>

force-app/main/default/objects/RunInSandbox__c/fields/Allow__c.field-meta.xml
<CustomField>
    <fullName>Allow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SimpleWebHookTest.cls
@IsTest
public class SimpleWebHookTest {

	@IsTest
	static void testSimpleWebHook() {

		RunInSandbox__c runInSandbox = new RunInSandbox__c( Allow__c = SimpleWebHook.runningInASandbox() );
		insert runInSandbox;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new SimpleWebHookMockHttpResponse());

		Id jobID = System.enqueueJob(
			new SimpleWebHookQueueable(
				'Hello',
				'World',
				'!!!'));

		jobID = System.enqueueJob(
			new SimpleWebHookQueueable());

		SimpleWebHookInvocable.webHookRequest request = new SimpleWebHookInvocable.webHookRequest();
		request.value1 = 'Hello World!!!';
		List<SimpleWebHookInvocable.webHookRequest> requests = new List<SimpleWebHookInvocable.webHookRequest>();
		requests.add(request);
		SimpleWebHookInvocable.sendWebHook(requests);

		Test.stopTest();
	}

	@IsTest
	static void testRunInSandbox() {

		RunInSandbox__c runInSandbox = new RunInSandbox__c( Allow__c = !SimpleWebHook.runningInASandbox() );
		insert runInSandbox;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new SimpleWebHookMockHttpResponse());

		SimpleWebHook wh = new SimpleWebHook();
		System.debug('\t*** simpleWebHook ***\n'+JSON.serializePretty(wh));
		wh.sendWebHook();

		Test.stopTest();
	}
}