force-app/main/default/objects/CallableQueue__e/CallableQueue__e.object-meta.xml
<CustomObject>
    <label>CallableQueue</label>
    <pluralLabel>CallableQueues</pluralLabel>
</CustomObject>

force-app/main/default/objects/CallableQueue__e/fields/action__c.field-meta.xml
<CustomField>
    <fullName>action__c</fullName>
    <label>action</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallableQueue__e/fields/args__c.field-meta.xml
<CustomField>
    <fullName>args__c</fullName>
    <label>args</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WebHookService.cls
/**
 * WebHookService
 */
@RestResource(urlMapping='/webhook')
global class WebHookService {

	/**
	 * doGet
	 */
	@HttpGet
	global static void doGet() {
		RestContext.response.addHeader('Content-Type', 'application/json');
		RestContext.response.responseBody = Blob.valueOf(JSON.serialize(RestContext.request.params));
   }

	/**
	 * doPost
	 * http -j POST https:/<force.com site>/services/apexrest/webhook action=getTeamMember args='{"arg1":"90008053"}'
	 */
	@HttpPost
	global static String doPost(String action, String args) {

		CallableQueue__e callQueue = new CallableQueue__e(
			action__c = action,
			args__c = args);

		Eventbus.publish(callQueue);

		return 'OK';
    }

}